import type { Category, Product } from '@/lib/types'

export const mockCategories: Category[] = [
  {
    id: 'category-electronics',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Smart devices and premium everyday tech.',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400',
    productCount: 3,
  },
  {
    id: 'category-fashion',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Modern wardrobe staples and elevated basics.',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400',
    productCount: 3,
  },
  {
    id: 'category-home-living',
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Clean, comfortable pieces for contemporary spaces.',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
    productCount: 2,
  },
  {
    id: 'category-sports-outdoors',
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description: 'Performance gear for active days outside.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    productCount: 2,
  },
  {
    id: 'category-beauty-health',
    name: 'Beauty & Health',
    slug: 'beauty-health',
    description: 'Self-care essentials with a premium feel.',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
    productCount: 1,
  },
  {
    id: 'category-books-media',
    name: 'Books & Media',
    slug: 'books-media',
    description: 'Stories, learning, and inspiration for everyday life.',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    productCount: 1,
  },
]

const categoryBySlug = new Map(mockCategories.map((category) => [category.slug, category]))

export const mockProducts: Product[] = [
  {
    id: 'product-aurora-headphones',
    name: 'Aurora Noise-Canceling Headphones',
    slug: 'aurora-noise-canceling-headphones',
    description: 'Premium over-ear headphones with immersive sound, deep bass, and all-day comfort.',
    price: 199,
    comparePrice: 249,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900'],
    categoryId: 'category-electronics',
    sku: 'ELEC-AURORA-001',
    stock: 18,
    featured: true,
    trending: true,
    rating: 4.8,
    reviewCount: 142,
    tags: ['audio', 'wireless', 'featured'],
    attributes: { color: 'Black', battery: '30 hours' },
    createdAt: '2026-03-10T10:00:00.000Z',
    updatedAt: '2026-03-20T10:00:00.000Z',
    category: categoryBySlug.get('electronics'),
  },
  {
    id: 'product-orbit-smartwatch',
    name: 'Orbit Smartwatch Pro',
    slug: 'orbit-smartwatch-pro',
    description: 'A sleek smartwatch with health tracking, GPS, and a bright always-on display.',
    price: 279,
    comparePrice: 329,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900'],
    categoryId: 'category-electronics',
    sku: 'ELEC-ORBIT-002',
    stock: 9,
    featured: true,
    trending: false,
    rating: 4.7,
    reviewCount: 96,
    tags: ['wearable', 'fitness'],
    attributes: { color: 'Silver', size: '44mm' },
    createdAt: '2026-03-12T10:00:00.000Z',
    updatedAt: '2026-03-21T10:00:00.000Z',
    category: categoryBySlug.get('electronics'),
  },
  {
    id: 'product-studio-speaker',
    name: 'Studio Portable Speaker',
    slug: 'studio-portable-speaker',
    description: 'Compact speaker with bold sound, waterproofing, and weekend-ready battery life.',
    price: 129,
    comparePrice: 159,
    images: ['https://images.unsplash.com/photo-1507878866276-a947ef722fee?w=900'],
    categoryId: 'category-electronics',
    sku: 'ELEC-STUDIO-003',
    stock: 24,
    featured: false,
    trending: true,
    rating: 4.6,
    reviewCount: 78,
    tags: ['speaker', 'portable'],
    attributes: { color: 'Navy', battery: '18 hours' },
    createdAt: '2026-03-01T10:00:00.000Z',
    updatedAt: '2026-03-19T10:00:00.000Z',
    category: categoryBySlug.get('electronics'),
  },
  {
    id: 'product-canvas-jacket',
    name: 'Canvas Utility Jacket',
    slug: 'canvas-utility-jacket',
    description: 'Structured lightweight jacket designed for layering across seasons.',
    price: 89,
    comparePrice: 119,
    images: ['https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=900'],
    categoryId: 'category-fashion',
    sku: 'FASH-CANVAS-004',
    stock: 31,
    featured: true,
    trending: false,
    rating: 4.5,
    reviewCount: 64,
    tags: ['jacket', 'menswear'],
    attributes: { material: 'Cotton blend', fit: 'Regular' },
    createdAt: '2026-02-28T10:00:00.000Z',
    updatedAt: '2026-03-18T10:00:00.000Z',
    category: categoryBySlug.get('fashion'),
  },
  {
    id: 'product-leather-sneakers',
    name: 'Everyday Leather Sneakers',
    slug: 'everyday-leather-sneakers',
    description: 'Minimal low-top sneakers built for comfort, clean lines, and daily wear.',
    price: 109,
    comparePrice: null,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900'],
    categoryId: 'category-fashion',
    sku: 'FASH-SNEAK-005',
    stock: 15,
    featured: false,
    trending: true,
    rating: 4.7,
    reviewCount: 121,
    tags: ['shoes', 'unisex'],
    attributes: { color: 'White', sole: 'Rubber' },
    createdAt: '2026-03-08T10:00:00.000Z',
    updatedAt: '2026-03-22T10:00:00.000Z',
    category: categoryBySlug.get('fashion'),
  },
  {
    id: 'product-tote-bag',
    name: 'Classic Everyday Tote',
    slug: 'classic-everyday-tote',
    description: 'Spacious tote with a refined silhouette for work, travel, and weekends.',
    price: 69,
    comparePrice: 89,
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=900'],
    categoryId: 'category-fashion',
    sku: 'FASH-TOTE-006',
    stock: 22,
    featured: false,
    trending: false,
    rating: 4.4,
    reviewCount: 51,
    tags: ['bag', 'accessories'],
    attributes: { material: 'Vegan leather', color: 'Tan' },
    createdAt: '2026-03-05T10:00:00.000Z',
    updatedAt: '2026-03-17T10:00:00.000Z',
    category: categoryBySlug.get('fashion'),
  },
  {
    id: 'product-lounge-chair',
    name: 'Nordic Lounge Chair',
    slug: 'nordic-lounge-chair',
    description: 'A soft upholstered accent chair with sculptural lines and oak legs.',
    price: 249,
    comparePrice: 319,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900'],
    categoryId: 'category-home-living',
    sku: 'HOME-CHAIR-007',
    stock: 6,
    featured: true,
    trending: false,
    rating: 4.9,
    reviewCount: 47,
    tags: ['furniture', 'living room'],
    attributes: { fabric: 'Boucle', color: 'Cream' },
    createdAt: '2026-02-26T10:00:00.000Z',
    updatedAt: '2026-03-15T10:00:00.000Z',
    category: categoryBySlug.get('home-living'),
  },
  {
    id: 'product-ceramic-lamp',
    name: 'Ceramic Table Lamp',
    slug: 'ceramic-table-lamp',
    description: 'Warm ambient lighting with a textured ceramic base and linen shade.',
    price: 79,
    comparePrice: 99,
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900'],
    categoryId: 'category-home-living',
    sku: 'HOME-LAMP-008',
    stock: 12,
    featured: false,
    trending: true,
    rating: 4.6,
    reviewCount: 38,
    tags: ['decor', 'lighting'],
    attributes: { color: 'Sand', height: '18 in' },
    createdAt: '2026-03-02T10:00:00.000Z',
    updatedAt: '2026-03-16T10:00:00.000Z',
    category: categoryBySlug.get('home-living'),
  },
  {
    id: 'product-training-duffel',
    name: 'Performance Training Duffel',
    slug: 'performance-training-duffel',
    description: 'Gym-ready duffel with ventilated compartments and weather-resistant fabric.',
    price: 74,
    comparePrice: null,
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=900'],
    categoryId: 'category-sports-outdoors',
    sku: 'SPORT-DUFFEL-009',
    stock: 19,
    featured: false,
    trending: true,
    rating: 4.5,
    reviewCount: 59,
    tags: ['gym', 'travel'],
    attributes: { capacity: '32L', color: 'Charcoal' },
    createdAt: '2026-03-03T10:00:00.000Z',
    updatedAt: '2026-03-14T10:00:00.000Z',
    category: categoryBySlug.get('sports-outdoors'),
  },
  {
    id: 'product-hiking-bottle',
    name: 'Insulated Hiking Bottle',
    slug: 'insulated-hiking-bottle',
    description: 'Double-wall bottle that keeps drinks cold for trails, commutes, and workouts.',
    price: 34,
    comparePrice: 44,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=900'],
    categoryId: 'category-sports-outdoors',
    sku: 'SPORT-BOTTLE-010',
    stock: 28,
    featured: false,
    trending: false,
    rating: 4.8,
    reviewCount: 84,
    tags: ['outdoors', 'hydration'],
    attributes: { size: '1L', insulation: '24 hours cold' },
    createdAt: '2026-03-09T10:00:00.000Z',
    updatedAt: '2026-03-23T10:00:00.000Z',
    category: categoryBySlug.get('sports-outdoors'),
  },
  {
    id: 'product-serum',
    name: 'Radiance Vitamin C Serum',
    slug: 'radiance-vitamin-c-serum',
    description: 'Brightening serum designed to smooth, hydrate, and add a healthy glow.',
    price: 39,
    comparePrice: 52,
    images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=900'],
    categoryId: 'category-beauty-health',
    sku: 'BEAUTY-SERUM-011',
    stock: 40,
    featured: true,
    trending: true,
    rating: 4.9,
    reviewCount: 173,
    tags: ['skincare', 'wellness'],
    attributes: { volume: '30ml', skinType: 'All' },
    createdAt: '2026-03-06T10:00:00.000Z',
    updatedAt: '2026-03-24T10:00:00.000Z',
    category: categoryBySlug.get('beauty-health'),
  },
  {
    id: 'product-design-book',
    name: 'Designing Better Interfaces',
    slug: 'designing-better-interfaces',
    description: 'A practical guide to product thinking, visual systems, and modern UX craft.',
    price: 29,
    comparePrice: null,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=900'],
    categoryId: 'category-books-media',
    sku: 'BOOK-UX-012',
    stock: 55,
    featured: false,
    trending: false,
    rating: 4.7,
    reviewCount: 88,
    tags: ['books', 'design'],
    attributes: { format: 'Paperback', pages: '320' },
    createdAt: '2026-03-11T10:00:00.000Z',
    updatedAt: '2026-03-25T10:00:00.000Z',
    category: categoryBySlug.get('books-media'),
  },
]

export function getMockCategories(): Category[] {
  return mockCategories.map((category) => ({ ...category }))
}

export function getMockProducts(): Product[] {
  return mockProducts.map((product) => ({
    ...product,
    images: [...product.images],
    tags: [...product.tags],
    attributes: { ...product.attributes },
    category: product.category ? { ...product.category } : undefined,
  }))
}
